name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2

    - name: Get .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.*'

    - name: dotnet publish
      run: |
        cd src/DesignsOfDotNet
        dotnet publish -c Release -o '../../artifacts/DesignsOfDotNet'

    - name: webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: designsofdotnet
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ./artifacts/DesignsOfDotNet
