name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2

    - name: Get .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.*'

    - name: dotnet build
      run: |
        cd src/DesignsOfDotNet
        dotnet build -c Release -o '../../artifacts/DesignsOfDotNet'
